// <auto-generated />
using System;
using MVC_day2_task1_the_lab_one.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_day2_task1_the_lab_one.Migrations
{
    [DbContext(typeof(InstituteContext))]
    [Migration("20240725102347_intial")]
    partial class intial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_day2_task1_the_lab_one.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("Hours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("degree")
                        .HasColumnType("int");

                    b.Property<int>("mindegree")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Name = "OOP",
                            degree = 100,
                            mindegree = 60
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Name = "HTML5",
                            degree = 100,
                            mindegree = 60
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Name = "CSS3",
                            degree = 100,
                            mindegree = 60
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            Name = "EF",
                            degree = 100,
                            mindegree = 60
                        });
                });

            modelBuilder.Entity("MVC_day2_task1_the_lab_one.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ManagerName = "ali",
                            Name = "DOT NET"
                        },
                        new
                        {
                            Id = 2,
                            ManagerName = "ahmed",
                            Name = "PHP"
                        },
                        new
                        {
                            Id = 3,
                            ManagerName = "omar",
                            Name = "CS"
                        },
                        new
                        {
                            Id = 4,
                            ManagerName = "amr",
                            Name = "SD"
                        });
                });

            modelBuilder.Entity("MVC_day2_task1_the_lab_one.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseID")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("salary")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CourseID");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseID = 1,
                            DepartmentId = 1,
                            Name = "ahmed",
                            address = "cairo",
                            image_url = "1.jpg",
                            salary = 12000m
                        },
                        new
                        {
                            Id = 2,
                            CourseID = 2,
                            DepartmentId = 2,
                            Name = "ali",
                            address = "alex",
                            image_url = "2.jpg",
                            salary = 12500m
                        },
                        new
                        {
                            Id = 3,
                            CourseID = 3,
                            DepartmentId = 3,
                            Name = "amr",
                            address = "monufia",
                            image_url = "3.jpg",
                            salary = 13000m
                        },
                        new
                        {
                            Id = 4,
                            CourseID = 4,
                            DepartmentId = 4,
                            Name = "omar",
                            address = "tanta",
                            image_url = "4.jpg",
                            salary = 14000m
                        });
                });

            modelBuilder.Entity("MVC_day2_task1_the_lab_one.Models.Traniee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Tranies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Grade = 98,
                            Name = "Ahmed",
                            address = "Alex",
                            imageUrl = "1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Grade = 88,
                            Name = "Ismael",
                            address = "Cairo",
                            imageUrl = "2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Grade = 78,
                            Name = "mohamed",
                            address = "Tanta",
                            imageUrl = "3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            Grade = 88,
                            Name = "Ahmed",
                            address = "Gia",
                            imageUrl = "4.jpg"
                        });
                });

            modelBuilder.Entity("MVC_day2_task1_the_lab_one.Models.TranieeCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Courseid")
                        .HasColumnType("int");

                    b.Property<int?>("TranieeId")
                        .HasColumnType("int");

                    b.Property<int>("degree")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Courseid");

                    b.HasIndex("TranieeId");

                    b.ToTable("tranieeCourses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Courseid = 2,
                            TranieeId = 1,
                            degree = 88
                        },
                        new
                        {
                            Id = 2,
                            Courseid = 1,
                            TranieeId = 1,
                            degree = 98
                        },
                        new
                        {
                            Id = 3,
                            Courseid = 3,
                            TranieeId = 1,
                            degree = 66
                        },
                        new
                        {
                            Id = 4,
                            Courseid = 4,
                            TranieeId = 1,
                            degree = 40
                        },
                        new
                        {
                            Id = 5,
                            Courseid = 1,
                            TranieeId = 2,
                            degree = 88
                        },
                        new
                        {
                            Id = 6,
                            Courseid = 4,
                            TranieeId = 2,
                            degree = 12
                        });
                });

            modelBuilder.Entity("MVC_day2_task1_the_lab_one.Models.Course", b =>
                {
                    b.HasOne("MVC_day2_task1_the_lab_one.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MVC_day2_task1_the_lab_one.Models.Instructor", b =>
                {
                    b.HasOne("MVC_day2_task1_the_lab_one.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID");

                    b.HasOne("MVC_day2_task1_the_lab_one.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MVC_day2_task1_the_lab_one.Models.Traniee", b =>
                {
                    b.HasOne("MVC_day2_task1_the_lab_one.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MVC_day2_task1_the_lab_one.Models.TranieeCourse", b =>
                {
                    b.HasOne("MVC_day2_task1_the_lab_one.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("Courseid");

                    b.HasOne("MVC_day2_task1_the_lab_one.Models.Traniee", "Traniee")
                        .WithMany()
                        .HasForeignKey("TranieeId");

                    b.Navigation("Course");

                    b.Navigation("Traniee");
                });

            modelBuilder.Entity("MVC_day2_task1_the_lab_one.Models.Department", b =>
                {
                    b.Navigation("Instructors");
                });
#pragma warning restore 612, 618
        }
    }
}
